### ISSUE TITLE
Task Make

### ISSUE THREAD

**Issue by eliezerazevedo** [thiagobraga/jojopaper.com.br#2]
Estou tentando escutar a task make e esta acusando comando invalido.
```
make : O termo 'make' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. Verifique a 
grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
No linha:1 caractere:1
+ make
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (make:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by thiagobraga** [comment]
Olá, @eliezerazevedo. Tudo bem?

Acredito que você esteja executando o script no Windows com o Powershell, por causa desse trecho do erro `...não é reconhecido como nome de cmdlet, função...`. O [`make`]() é uma ferramenta de automação de tarefas, muito comum no Linux. Como você está no Windows, você teria duas opções:

- Instalar o Ubuntu no WSL
https://docs.microsoft.com/pt-br/windows/wsl/install-win10
  -  E depois, instalar o `make`, se já não vir instalado
  `sudo apt-get install build-essential`
- Ou então, instalar o [**Make for Windows**](http://gnuwin32.sourceforge.net/packages/make.htm)

Creio que fazendo isso, você vai conseguir rodar o `make`.

**Comment by eliezerazevedo** [comment]
Obrigado pela ajuda, entrei agora pelo meu ubuntu para tentar rodar o make.

`root@eliezer-pc:/home/eliezerazevedo/Projetos/jojopaper.com.br# cd certs && mkcert local.jojopaper.com.br && cd -Using the local CA at "/root/.local/share/mkcert" ✨
Warning: the local CA is not installed in the Firefox and/or Chrome/Chromium trust store! ⚠️
Run "mkcert -install" to avoid verification errors ‼️

Created a new certificate valid for the following names 📜
 - "local.jojopaper.com.br"

The certificate is at "./local.jojopaper.com.br.pem" and the key at "./local.jojopaper.com.br-key.pem" ✅

/home/eliezerazevedo/Projetos/jojopaper.com.br
root@eliezer-pc:/home/eliezerazevedo/Projetos/jojopaper.com.br# make
make: *** [Makefile:11: install] Erro 1
root@eliezer-pc:/home/eliezerazevedo/Projetos/jojopaper.com.br# `

Tem alguma extensão ou dependência que precisa ser instalada além do build-essential?

**Comment by thiagobraga** [comment]
Legal, o primeiro comando deu certo, criou um certificado SSL com o `mkcert`.

Agora o erro no `make`, você pode executar `make -n` na raiz do projeto para ver o que o make está tentando executar, assim conseguimos investigar qual ponto pode estar dando erro (se é a sintaxe do make ou se é algo que o make está tentando executar e não consegue). No caso, ele deve emitir este output:

```sh
rm -rf theme.css node_modules
if [ ! -d node_modules ]; then yarn; fi
sass -s compressed --no-charset --no-source-map src/sass:.
css2userstyle --no-userscript theme.css
chokidar src/sass -c 'make -s build' & \
        browser-sync start --config bs-config.js & \
        wait
```

---

Eu acredito que o erro seja por você não ter instalado o [**yarn**](https://classic.yarnpkg.com). Você pode instalá-lo diretamente [como package do Ubuntu](https://classic.yarnpkg.com/en/docs/install#debian-stable):

```sh
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
```

> Você precisará do `curl`, então caso não tenha no seu Ubuntu
> ```sh
> sudo apt install curl
> ```

---

Ou então, se você tiver [**npm**](https://www.npmjs.com/get-npm), você pode instalar o yarn com:

```sh
npm i -g yarn
```

Em seguida, acredito que o make conseguirá executar tudo.

Vou aproveitar sua issue para editar o `README.md` incluindo os requisitos do projeto.

**Comment by eliezerazevedo** [comment]
Finalmente consegui, estou tentado aprender agora programação obrigado pela ajuda e paciência. 
A solução foi deletar o arquivo yarn.look antes de rodar o comando:
`yarn install`
Realmente estava faltando instalar.

`root@eliezer-pc:/home/eliezerazevedo/Projetos/lepotibabystore.com.br# make
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 1.55s.
Watching "src/sass" ..
[Browsersync] Proxying: https://www.lepotibabystore.com.br
[Browsersync] Access URLs:
 ---------------------------------------------------
    Local: https://localhost:3000
 External: https://local.lepotibabystore.com.br:3000
 ---------------------------------------------------
[Browsersync] Watching files...`
